---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 2857722531-bZSzkm1Wuef2s95y7snYlveUzRwo3b8zPQoerma
:access_token_secret: eaqzBRhhuebvI9IfLTLuTrRfnCU1It4Us3PLQ5iIIb8JT
